config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :bookshelves
  resources :users

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"

  get "/books/:id/add" => "books#add"

  root "sessions#new"

  

end

app/controllers/bookshelves_controller.rb
class BookshelvesController < ApplicationController
  before_action :set_bookshelf, only: [:show, :edit, :update, :destroy]

  # GET /bookshelves
  # GET /bookshelves.json
  def index
    @bookshelves = Bookshelf.all
  end

  # GET /bookshelves/1
  # GET /bookshelves/1.json
  def show
  end

  # GET /bookshelves/new
  def new
    @bookshelf = Bookshelf.new
    @bookshelf.user = User.find_by(email: session[:email])
  end

  # GET /bookshelves/1/edit
  def edit
  end

  # POST /bookshelves
  # POST /bookshelves.json
  def create

    @bookshelf = Bookshelf.new(bookshelf_params)
    @bookshelf.user = User.find_by(email: session[:email])
    #puts "\n\n"
    #puts @bookshelf.user_id
    #puts "\n\n"

    respond_to do |format|
      if @bookshelf.save
        format.html { redirect_to @bookshelf, notice: 'Bookshelf was successfully created.' }
        format.json { render :show, status: :created, location: @bookshelf }
      else
        format.html { render :new }
        format.json { render json: @bookshelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookshelves/1
  # PATCH/PUT /bookshelves/1.json
  def update
    respond_to do |format|
      if @bookshelf.update(bookshelf_params)
        format.html { redirect_to @bookshelf, notice: 'Bookshelf was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookshelf }
      else
        format.html { render :edit }
        format.json { render json: @bookshelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookshelves/1
  # DELETE /bookshelves/1.json
  def destroy
    @bookshelf.destroy
    respond_to do |format|
      format.html { redirect_to bookshelves_url, notice: 'Bookshelf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookshelf
      @bookshelf = Bookshelf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookshelf_params
      params.require(:bookshelf).permit(:title)
    end
end

app/helpers/bookshelves_helper.rb
module BookshelvesHelper
end

app/views/bookshelves/_form.html.erb
<%= form_for(@bookshelf) do |f| %>
  <% if @bookshelf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookshelf.errors.count, "error") %> prohibited this bookshelf from being saved:</h2>

      <ul>
      <% @bookshelf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookshelves/edit.html.erb
<h1>Editing Bookshelf</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookshelf %> |
<%= link_to 'Back', bookshelves_path %>

<br>
<br>

app/views/bookshelves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookshelves</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookshelves.each do |bookshelf| %>
      <tr>
        <td><%= bookshelf.title %></td>
        <td><%= link_to 'Show', bookshelf %></td>
        <td><%= link_to 'Edit', edit_bookshelf_path(bookshelf) %></td>
        <td><%= link_to 'Destroy', bookshelf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookshelf', new_bookshelf_path %>

app/views/bookshelves/new.html.erb
<h1>New Bookshelf</h1>

<%= render 'form' %>

<%= link_to 'Back', bookshelves_path %>

app/views/bookshelves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookshelf.title %>
</p>

<p>
  <strong>Current Books:</strong>
  <% @shelves = @bookshelf.books %>
  <% @shelves.each do |shelf| %>
  <tr>
    <td> <%= shelf.title %></td>
  </tr>
  <% end %>
</p>

<p>
  <strong>Owner:</strong>
  <% @usr = @bookshelf.user %>
  <tr>
    <td> <%= @usr.email %></td>
  </tr>
</p>
<%= link_to 'Edit', edit_bookshelf_path(@bookshelf) %> |
<%= link_to 'Back', bookshelves_path %>